#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FotoABIld.Droid.Resource", IsApplication=true)]

namespace FotoABIld.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int photo_height = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int photo_width = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_sel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkbox_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkbox_up = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hamburgermeny = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Hamburgermenyv2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Henrik = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Johan = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int no_media = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int on_focus_checkbox = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int richard = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int top_bar = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001e
			public const int BaseContainer = 2131165214;
			
			// aapt resource value: 0x7f070005
			public const int CancelButton = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int ChoosePicturesButton = 2131165191;
			
			// aapt resource value: 0x7f070020
			public const int FlyOutMenu = 2131165216;
			
			// aapt resource value: 0x7f07001b
			public const int FlyOutMenuButton = 2131165211;
			
			// aapt resource value: 0x7f070025
			public const int HelpText = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int HistoryText = 2131165220;
			
			// aapt resource value: 0x7f07001f
			public const int HomeButton = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int HomeText = 2131165218;
			
			// aapt resource value: 0x7f070006
			public const int NextButton = 2131165190;
			
			// aapt resource value: 0x7f070023
			public const int OrderText = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int SideMenu = 2131165217;
			
			// aapt resource value: 0x7f070016
			public const int btnGalleryOk = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int editText1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int editText2 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int editText3 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int editText4 = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int editText5 = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int edit_picture = 2131165197;
			
			// aapt resource value: 0x7f070017
			public const int frmQueue = 2131165207;
			
			// aapt resource value: 0x7f070013
			public const int gridGallery = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int gridview = 2131165192;
			
			// aapt resource value: 0x7f07001d
			public const int historyButton = 2131165213;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int imgNoMedia = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int imgQueue = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int imgQueueMultiSelected = 2131165209;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout4 = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout6 = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout7 = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int llBottomContainer = 2131165205;
			
			// aapt resource value: 0x7f07001a
			public const int mainLayout = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int numberLabel = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int numberPicker1 = 2131165200;
			
			// aapt resource value: 0x7f07001c
			public const int orderButton = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int textView1 = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChangePictureSize = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChoosePictures = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomerInformation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditPicture = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FinalizeOrder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int gallery = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int gallery_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HelpPage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainFrame = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int OrderHistory = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SideMenuLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int titlebar = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
