#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FotoABIld.Droid.Resource", IsApplication=true)]

namespace FotoABIld.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Sizes = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int backgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010012
			public const int cropEnabled = 2130771986;
			
			// aapt resource value: 0x7f010005
			public const int cropMode = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int cropviewMaxScale = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cropviewMinScale = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int cropviewViewportHeaderFooterColor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int cropviewViewportHeightRatio = 2130771968;
			
			// aapt resource value: 0x7f010008
			public const int frameColor = 2130771976;
			
			// aapt resource value: 0x7f010010
			public const int frameStrokeWeight = 2130771984;
			
			// aapt resource value: 0x7f01000a
			public const int guideColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int guideShowMode = 2130771979;
			
			// aapt resource value: 0x7f010011
			public const int guideStrokeWeight = 2130771985;
			
			// aapt resource value: 0x7f010009
			public const int handleColor = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int handleShowMode = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int handleSize = 2130771981;
			
			// aapt resource value: 0x7f010004
			public const int imgSrc = 2130771972;
			
			// aapt resource value: 0x7f010013
			public const int initialFrameScale = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int minFrameSize = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int overlayColor = 2130771975;
			
			// aapt resource value: 0x7f01000e
			public const int touchPadding = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int photo_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int photo_width = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_sel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkbox_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkbox_up = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hamburgermeny = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Hamburgermenyv2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Henrik = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_content_add = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_content_content_cut = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Johan = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int no_media = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int on_focus_checkbox = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int richard = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int top_bar = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int trash_can = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080050
			public const int BackButton = 2131230800;
			
			// aapt resource value: 0x7f08003d
			public const int BaseContainer = 2131230781;
			
			// aapt resource value: 0x7f080011
			public const int CancelButton = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int ChoosePicturesButton = 2131230739;
			
			// aapt resource value: 0x7f080020
			public const int CustomerInfoEmailText = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int CustomerInfoNameText = 2131230749;
			
			// aapt resource value: 0x7f08001f
			public const int CustomerInfoPhoneNumber = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int CustomerInfoSurnameText = 2131230750;
			
			// aapt resource value: 0x7f080056
			public const int FlyOutMenu = 2131230806;
			
			// aapt resource value: 0x7f08003a
			public const int FlyOutMenuButton = 2131230778;
			
			// aapt resource value: 0x7f08005c
			public const int HelpText = 2131230812;
			
			// aapt resource value: 0x7f08005a
			public const int HistoryText = 2131230810;
			
			// aapt resource value: 0x7f080043
			public const int HomeButton = 2131230787;
			
			// aapt resource value: 0x7f080058
			public const int HomeText = 2131230808;
			
			// aapt resource value: 0x7f080012
			public const int NextButton = 2131230738;
			
			// aapt resource value: 0x7f080059
			public const int OrderText = 2131230809;
			
			// aapt resource value: 0x7f080031
			public const int PlaceOrderButton = 2131230769;
			
			// aapt resource value: 0x7f08005b
			public const int PriceText = 2131230811;
			
			// aapt resource value: 0x7f080028
			public const int RelativeLayout = 2131230760;
			
			// aapt resource value: 0x7f080044
			public const int RemoveHistoryButton = 2131230788;
			
			// aapt resource value: 0x7f080057
			public const int SideMenu = 2131230807;
			
			// aapt resource value: 0x7f080049
			public const int amountText = 2131230793;
			
			// aapt resource value: 0x7f080034
			public const int btnGalleryOk = 2131230772;
			
			// aapt resource value: 0x7f080042
			public const int buttonViewSwitcher = 2131230786;
			
			// aapt resource value: 0x7f080000
			public const int circle = 2131230720;
			
			// aapt resource value: 0x7f080027
			public const int copyButton = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int cropButton = 2131230758;
			
			// aapt resource value: 0x7f080017
			public const int cropImageView = 2131230743;
			
			// aapt resource value: 0x7f08001b
			public const int cropbutton1 = 2131230747;
			
			// aapt resource value: 0x7f080018
			public const int croppedImageView = 2131230744;
			
			// aapt resource value: 0x7f080041
			public const int deleteListView = 2131230785;
			
			// aapt resource value: 0x7f08001c
			public const int doneButton = 2131230748;
			
			// aapt resource value: 0x7f080021
			public const int edit_picture = 2131230753;
			
			// aapt resource value: 0x7f08002e
			public const int emailLayout = 2131230766;
			
			// aapt resource value: 0x7f08004b
			public const int emailMessageText = 2131230795;
			
			// aapt resource value: 0x7f080046
			public const int expectedCollectText = 2131230790;
			
			// aapt resource value: 0x7f080029
			public const int finalCheck = 2131230761;
			
			// aapt resource value: 0x7f080054
			public const int finalPrice = 2131230804;
			
			// aapt resource value: 0x7f08002f
			public const int finalizeEmail = 2131230767;
			
			// aapt resource value: 0x7f08002b
			public const int finalizeNameSurnameText = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int finalizePhoneNumber = 2131230765;
			
			// aapt resource value: 0x7f080035
			public const int frmQueue = 2131230773;
			
			// aapt resource value: 0x7f080015
			public const int gridGallery = 2131230741;
			
			// aapt resource value: 0x7f08003c
			public const int historyButton = 2131230780;
			
			// aapt resource value: 0x7f08004c
			public const int homeButton = 2131230796;
			
			// aapt resource value: 0x7f08000e
			public const int imageView1 = 2131230734;
			
			// aapt resource value: 0x7f080032
			public const int imgNoMedia = 2131230770;
			
			// aapt resource value: 0x7f080036
			public const int imgQueue = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int imgQueueMultiSelected = 2131230775;
			
			// aapt resource value: 0x7f080016
			public const int imgSinglePick = 2131230742;
			
			// aapt resource value: 0x7f08003f
			public const int itemListViewSwitcher = 2131230783;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout2 = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout3 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout4 = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout6 = 2131230732;
			
			// aapt resource value: 0x7f080022
			public const int linearLayout7 = 2131230754;
			
			// aapt resource value: 0x7f08005d
			public const int listItemCheckBox = 2131230813;
			
			// aapt resource value: 0x7f08004d
			public const int listItemText = 2131230797;
			
			// aapt resource value: 0x7f080033
			public const int llBottomContainer = 2131230771;
			
			// aapt resource value: 0x7f080039
			public const int mainLayout = 2131230777;
			
			// aapt resource value: 0x7f08002a
			public const int nameLayout = 2131230762;
			
			// aapt resource value: 0x7f080047
			public const int nameText = 2131230791;
			
			// aapt resource value: 0x7f080009
			public const int not_show = 2131230729;
			
			// aapt resource value: 0x7f080023
			public const int numberLabel = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int numberPicker1 = 2131230756;
			
			// aapt resource value: 0x7f08003b
			public const int orderButton = 2131230779;
			
			// aapt resource value: 0x7f080040
			public const int orderListView = 2131230784;
			
			// aapt resource value: 0x7f080045
			public const int orderNumberText = 2131230789;
			
			// aapt resource value: 0x7f08002c
			public const int phoneNumberLayout = 2131230764;
			
			// aapt resource value: 0x7f080048
			public const int phoneNumberText = 2131230792;
			
			// aapt resource value: 0x7f08004a
			public const int priceText = 2131230794;
			
			// aapt resource value: 0x7f08004f
			public const int pricetext = 2131230799;
			
			// aapt resource value: 0x7f080001
			public const int ratio_16_9 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ratio_1_1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int ratio_3_4 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int ratio_4_3 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ratio_9_16 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int ratio_custom = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int ratio_fit_image = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int ratio_free = 2131230728;
			
			// aapt resource value: 0x7f080051
			public const int receiptlayout = 2131230801;
			
			// aapt resource value: 0x7f080052
			public const int receipttext = 2131230802;
			
			// aapt resource value: 0x7f08001a
			public const int rotateButton = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int rotateCropView = 2131230745;
			
			// aapt resource value: 0x7f08004e
			public const int scrollView1 = 2131230798;
			
			// aapt resource value: 0x7f08000a
			public const int show_always = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int show_on_touch = 2131230731;
			
			// aapt resource value: 0x7f080025
			public const int spinner = 2131230757;
			
			// aapt resource value: 0x7f080053
			public const int summarizeOrder = 2131230803;
			
			// aapt resource value: 0x7f080030
			public const int summarizePictures = 2131230768;
			
			// aapt resource value: 0x7f080038
			public const int textView1 = 2131230776;
			
			// aapt resource value: 0x7f080055
			public const int thankText = 2131230805;
			
			// aapt resource value: 0x7f08003e
			public const int trashCanIcon = 2131230782;
			
			// aapt resource value: 0x7f080014
			public const int viewSwitcher = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChangePictureSize = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChoosePictures = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CropImage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomerInformation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditPicture = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FinalizeOrder = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int gallery = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int gallery_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HelpPage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MainFrame = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int OrderHistory = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int OrderHistoryItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int OrderHistoryListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PricesSizes = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Receipt = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SideMenuLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int titlebar = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int TrashCheckBox = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int amount = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int date = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int price = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int priceandsize = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CropImageView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int CropImageView_backgroundColor = 2;
			
			// aapt resource value: 14
			public const int CropImageView_cropEnabled = 14;
			
			// aapt resource value: 1
			public const int CropImageView_cropMode = 1;
			
			// aapt resource value: 4
			public const int CropImageView_frameColor = 4;
			
			// aapt resource value: 12
			public const int CropImageView_frameStrokeWeight = 12;
			
			// aapt resource value: 6
			public const int CropImageView_guideColor = 6;
			
			// aapt resource value: 7
			public const int CropImageView_guideShowMode = 7;
			
			// aapt resource value: 13
			public const int CropImageView_guideStrokeWeight = 13;
			
			// aapt resource value: 5
			public const int CropImageView_handleColor = 5;
			
			// aapt resource value: 8
			public const int CropImageView_handleShowMode = 8;
			
			// aapt resource value: 9
			public const int CropImageView_handleSize = 9;
			
			// aapt resource value: 0
			public const int CropImageView_imgSrc = 0;
			
			// aapt resource value: 15
			public const int CropImageView_initialFrameScale = 15;
			
			// aapt resource value: 11
			public const int CropImageView_minFrameSize = 11;
			
			// aapt resource value: 3
			public const int CropImageView_overlayColor = 3;
			
			// aapt resource value: 10
			public const int CropImageView_touchPadding = 10;
			
			public static int[] CropView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 2
			public const int CropView_cropviewMaxScale = 2;
			
			// aapt resource value: 3
			public const int CropView_cropviewMinScale = 3;
			
			// aapt resource value: 1
			public const int CropView_cropviewViewportHeaderFooterColor = 1;
			
			// aapt resource value: 0
			public const int CropView_cropviewViewportHeightRatio = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
